- name: General update and rolling reboot
  hosts: all
  serial: 2
  tasks:
    - name: Update and upgrade apt packages
      become: true
      become_user: root
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 86400 # One day
    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists
