- name: Update workers using apt.
  hosts: workers
  tasks:
    - name: Update all packages to their latest version
      become: true
      become_user: root
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Reboot box if kernel/libs updated and requested by the system
      ansible.builtin.shell: 
        cmd: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed'
        removes: /var/run/reboot-required
      async: 300
      poll: 0
      ignore_errors: true
    - name: Wait for system to become reachable again
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300
    - name: Verify new update (optional)
      ansible.builtin.command: uname -mrs
      register: uname_result
    - name: Display new kernel version
      ansible.builtin.debug:
        var: uname_result.stdout_lines
